"use client";
import {useEffect,useMemo,useState} from "react";
import {geoNaturalEarth1,geoPath} from "d3-geo";
import {feature} from "topojson-client";
// @ts-expect-error
import world from "world-atlas/countries-110m.json";

type Capital={country:string;iso2:string;iso3:string;capital:string;lat:number;lon:number;region:string};
type Decision={step:number;from:Capital;selected:Capital;candidates:{city:Capital;score:number;confidence:number}[];distanceKm:number;confidence:number};
type Result={algorithm:string;route:Capital[];distanceKm:number;runtimeMs:number;decisions:Decision[]};

const START:Capital={country:"India",iso2:"IN",iso3:"IND",capital:"Bengaluru",lat:12.9716,lon:77.5946,region:"Asia"};
const ISO195=new Set("AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG BF BI CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT HN HU IS IN ID IR IQ IE IL IT JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW MY MV ML MT MH MR MU MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO OM PK PW PA PG PY PE PH PL PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG SK SI SB SO ZA SS ES LK SD SR SE CH SY TJ TZ TH TL TG TO TT TN TR TM TV UG UA AE GB US UY UZ VU VA VE VN YE ZM ZW PS".split(" "));
const conventions:Record<string,string>={BO:"Sucre",LK:"Sri Jayawardenepura Kotte",ZA:"Pretoria",TZ:"Dodoma",PS:"Ramallah"};
function hav(a:Capital,b:Capital){const r=6371.0088,p=Math.PI/180,d1=(b.lat-a.lat)*p,d2=(b.lon-a.lon)*p,x=Math.sin(d1/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(d2/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function dist(r:Capital[]){let d=0;for(let i=0;i<r.length-1;i++)d+=hav(r[i],r[i+1]);return d}
function rng(seed:number){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function randomRoute(c:Capital[],seed=20260919){const a=[...c],r=rng(seed);for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return[START,...a,START]}
function nearest(c:Capital[]){const a=[...c],out=[START];let cur=START;while(a.length){let bi=0,bd=Infinity;for(let i=0;i<a.length;i++){const d=hav(cur,a[i]);if(d<bd){bd=d;bi=i}}cur=a.splice(bi,1)[0];out.push(cur)}out.push(START);return out}
function twoOpt(route:Capital[]){const o=[...route];let improved=true,loops=0;while(improved&&loops++<1000){improved=false;for(let i=1;i<o.length-3;i++)for(let j=i+1;j<o.length-1;j++){const old=hav(o[i-1],o[i])+hav(o[j],o[j+1]),neu=hav(o[i-1],o[j])+hav(o[i],o[j+1]);if(neu<old-1e-7){o.splice(i,j-i+1,...o.slice(i,j+1).reverse());improved=true}}}return o}
function candidates(cur:Capital,rem:Capital[],seed:number){const a=[...rem].sort((x,y)=>hav(cur,x)-hav(cur,y));const p=a.slice(0,3);p.push(...rem.filter(x=>x.region===cur.region&&!p.includes(x)).slice(0,2));const far=[...rem].sort((x,y)=>hav(cur,y)-hav(cur,x));if(far[0])p.push(far[Math.floor(rng(seed)()*Math.min(5,far.length))]);while(p.length<8&&rem.length){const x=rem[Math.floor(rng(seed+p.length)()*rem.length)];if(!p.includes(x))p.push(x)}return p.slice(0,8)}
function jev(c:Capital[]){let cur=START,rem=[...c],route=[START],ds:Decision[]=[];while(rem.length){const cs=candidates(cur,rem,route.length*19);const ranked=cs.map(x=>{const local=hav(cur,x),rest=rem.filter(y=>y!==x),future=rest.length?Math.min(...rest.map(y=>hav(x,y))):0,s=1/(1+local/2500)+.35/(1+future/1800)+.12*(x.region===cur.region?1:0);return{city:x,score:s,confidence:s}}).sort((a,b)=>b.score-a.score);const max=ranked[0].score;const norm=ranked.map(x=>({...x,confidence:Math.min(.99,Math.max(.35,.08+.92*x.score/max))}));const pick=norm[0].city;ds.push({step:route.length,from:cur,selected:pick,candidates:norm,distanceKm:hav(cur,pick),confidence:norm[0].confidence});route.push(pick);rem=rem.filter(x=>x!==pick);cur=pick}route.push(START);return{route,decisions:ds}}
async function load():Promise<Capital[]>{const r=await fetch("https://raw.githubusercontent.com/Stefie/geojson-world/master/capitals.geojson");if(!r.ok)throw Error("Capital dataset unavailable");const j=await r.json(),m=new Map<string,Capital>();for(const f of j.features||[]){const p=f.properties||{},id=p.iso2||f.id;if(!ISO195.has(id)||!p.city||!f.geometry?.coordinates)continue;m.set(id,{country:p.country,iso2:id,iso3:p.iso3,capital:conventions[id]||p.city,lon:f.geometry.coordinates[0],lat:f.geometry.coordinates[1],region:"Other"})}const ov:Record<string,[number,number]>={LK:[6.9271,79.8612],BO:[-19.0196,-65.2619],ZA:[-25.7479,28.2293],TZ:[-6.163,35.7516],PS:[31.9038,35.2034],IN:[28.6139,77.209]};for(const k in ov)if(m.has(k)){m.get(k)!.lat=ov[k][0];m.get(k)!.lon=ov[k][1]}const out=[...m.values()].sort((a,b)=>a.country.localeCompare(b.country));if(out.length!==195)throw Error("Expected 195 capitals, found "+out.length);return out}

export default function Home(){const[cities,setCities]=useState<Capital[]>([]),[err,setErr]=useState(""),[result,setResult]=useState<Result|null>(null),[bench,setBench]=useState<Result[]>([]),[step,setStep]=useState(0),[speed,setSpeed]=useState(1),[algorithm,setAlgorithm]=useState("JEV Demo + 2-opt"),[region,setRegion]=useState("All"),[showCandidates,setShowCandidates]=useState(true),[running,setRunning]=useState(false);useEffect(()=>{load().then(setCities).catch(e=>setErr(e.message))},[]);
const features=useMemo(()=>feature(world as any,(world as any).objects.countries) as any,[]),projection=useMemo(()=>geoNaturalEarth1().fitSize([1000,510],features),[features]),path=useMemo(()=>geoPath(projection),[projection]);const route=result?.route||[],visible=running?route.slice(0,Math.max(1,step+1)):route,current=visible[visible.length-1]||START,decision=result?.decisions.find(x=>x.step===step),filtered=cities.filter(x=>region==="All"||x.region===region),line=visible.map(x=>projection([x.lon,x.lat])?.join(",")).filter(Boolean).join(" ");
function run(){if(!cities.length)return;let r:Result;const t=performance.now();if(algorithm==="Random"){const x=randomRoute(cities);r={algorithm,route:x,distanceKm:dist(x),runtimeMs:performance.now()-t,decisions:[]}}else if(algorithm==="Nearest Neighbor"){const x=nearest(cities);r={algorithm,route:x,distanceKm:dist(x),runtimeMs:performance.now()-t,decisions:[]}}else if(algorithm==="NN + 2-opt"){const x=twoOpt(nearest(cities));r={algorithm,route:x,distanceKm:dist(x),runtimeMs:performance.now()-t,decisions:[]}}else{const j=jev(cities),x=algorithm==="JEV Demo + 2-opt"?twoOpt(j.route):j.route;r={algorithm,route:x,distanceKm:dist(x),runtimeMs:performance.now()-t,decisions:j.decisions}}setResult(r);setStep(0);setRunning(true);(async()=>{for(let i=1;i<r.route.length;i++){await new Promise(x=>setTimeout(x,Math.max(8,180/speed)));setStep(i)}setRunning(false)})()}
function benchmark(){if(!cities.length)return;const t=(fn:()=>Result)=>{const s=performance.now(),r=fn();r.runtimeMs=performance.now()-s;return r};const n=nearest(cities),j=jev(cities),a=[t(()=>({algorithm:"Random",route:randomRoute(cities),distanceKm:0,runtimeMs:0,decisions:[]})),t(()=>({algorithm:"Nearest Neighbor",route:n,distanceKm:dist(n),runtimeMs:0,decisions:[]})),t(()=>{const x=twoOpt(n);return{algorithm:"NN + 2-opt",route:x,distanceKm:dist(x),runtimeMs:0,decisions:[]}}),t(()=>({algorithm:"JEV Demo",route:j.route,distanceKm:dist(j.route),runtimeMs:0,decisions:j.decisions})),t(()=>{const x=twoOpt(j.route);return{algorithm:"JEV Demo + 2-opt",route:x,distanceKm:dist(x),runtimeMs:0,decisions:j.decisions}})];a[0].distanceKm=dist(a[0].route);setBench(a)}
if(err)return <main className="shell"><div className="error">DATASET ERROR<span>{err}</span></div></main>;
return <main className="shell"><header className="topbar"><div><div className="eyebrow">JEV / SYSTEM ONE EXPERIMENT</div><h1>WORLD<span>TOUR</span></h1><p>Can an AI decision model navigate the world?</p></div><div className="status"><span className="dot"/><div>JEV DEMO</div><small>Deterministic provider</small></div></header>
<section className="hero"><div><strong>195</strong><span>CAPITALS</span></div><div><strong>196</strong><span>LEGS</span></div><div><strong>{result?result.distanceKm.toLocaleString(undefined,{maximumFractionDigits:0})+" km":"—"}</strong><span>ROUTE DISTANCE</span></div><div><strong>{result?.decisions.length||0}</strong><span>JEV DECISIONS</span></div></section>
<section className="controls"><button onClick={run} disabled={!cities.length}>{running?"RUNNING":"RUN JEV"}</button><button className="ghost" onClick={benchmark} disabled={!cities.length}>BENCHMARK ALL</button><label>ALGORITHM<select value={algorithm} onChange={e=>setAlgorithm(e.target.value)}><option>JEV Demo + 2-opt</option><option>JEV Demo</option><option>NN + 2-opt</option><option>Nearest Neighbor</option><option>Random</option></select></label><label>SPEED<select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value="0.5">0.5×</option><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></section>
<section className="mapCard"><div className="mapHead"><div><b>WORLD ROUTE</b><span>START / END · BENGALURU, INDIA</span></div><div className="filters"><select value={region} onChange={e=>setRegion(e.target.value)}><option>All</option></select><label><input type="checkbox" checked={showCandidates} onChange={e=>setShowCandidates(e.target.checked)}/> candidates</label></div></div><svg viewBox="0 0 1000 510" className="map"><g className="land">{features.features.map((f:any,i:number)=><path key={i} d={path(f)||""}/>)}</g>{line&&<polyline points={line} className="route"/>}{filtered.map(c=>{const p=projection([c.lon,c.lat]);if(!p)return null;const active=c.iso2===current.iso2,cand=showCandidates&&(decision?.candidates.some(x=>x.city.iso2===c.iso2)||false);return <g key={c.iso2} className={active?"capital active":cand?"capital candidate":"capital"}><circle cx={p[0]} cy={p[1]} r={active?5:cand?4:2.2}/><title>{c.capital+", "+c.country}</title></g>})}</svg></section>
<section className="grid"><div className="panel"><div className="panelTitle">JEV DECISION TRACE <span>{decision?"#"+decision.step:"—"}</span></div>{decision?<><div className="decisionCurrent"><small>CURRENT</small><b>{decision.from.capital}</b><span>{decision.from.country}</span></div><div className="decisionPick"><small>SELECTED</small><b>{decision.selected.capital}</b><span>{decision.selected.country+" · "+decision.distanceKm.toFixed(0)+" km"}</span><em>{Math.round(decision.confidence*100)}%</em></div><div className="candidates">{decision.candidates.map((x,i)=><div key={x.city.iso2}><span>{String(i+1).padStart(2,"0")}</span><b>{x.city.capital}</b><i>{Math.round(x.confidence*100)}%</i><meter min="0" max="1" value={x.confidence}/></div>)}</div></>:<div className="empty">Run JEV to inspect candidate decisions.</div>}</div><div className="panel routePanel"><div className="panelTitle">ROUTE <span>{visible.length?Math.min(step,195)+"/195":"READY"}</span></div><div className="routeList">{visible.slice(0,80).map((c,i)=><div key={i} className={i===visible.length-1?"currentRow":""}><span>{String(i).padStart(3,"0")}</span><b>{c.capital}</b><small>{c.country}</small>{i<visible.length-1&&<i>{hav(c,visible[i+1]).toFixed(0)} km</i>}</div>)}{visible.length>80&&<div className="more">+ {visible.length-80} more legs</div>}</div></div></section>
<section className="benchmark panel"><div className="panelTitle">BENCHMARK <span>SEED 20260919 · SAME DATASET</span></div>{bench.length?bench.map(x=><div className="benchRow" key={x.algorithm}><b>{x.algorithm}</b><div className="bar"><span style={{width:(Math.max(3,100*x.distanceKm/Math.max(...bench.map(y=>y.distanceKm)))+"%")}}/></div><strong>{x.distanceKm.toLocaleString(undefined,{maximumFractionDigits:0})+" km"}</strong><small>{x.runtimeMs.toFixed(1)+" ms"}</small></div>):<div className="empty">Run the benchmark to compare all methods.</div>}</section>
<footer><span>✓ {cities.length||"—"} / 195 capitals loaded</span><span>Great-circle · R = 6371.0088 km</span><span>Heuristic benchmark — not a proof of global optimum</span></footer></main>}