import {NextResponse} from "next/server";
type Capital={country:string;iso2:string;iso3:string;capital:string;lat:number;lon:number;region:string};
type DistanceFeature={iso2:string;currentKm:number;nearestFutureKm:number;farthestFutureKm:number};
type DecideRequest={step:number;current:Capital;candidates:Capital[];remaining:Capital[];mode?:"geographic"|"distance"|"matrix";distanceFeatures?:DistanceFeature[];distanceMatrix?:Record<string,Record<string,number>>};
function hav(a:Capital,b:Capital){const r=6371.0088,p=Math.PI/180,d1=(b.lat-a.lat)*p,d2=(b.lon-a.lon)*p,x=Math.sin(d1/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(d2/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function demoRank(current:Capital,candidates:Capital[],remaining:Capital[]){const scored=candidates.map(c=>{const local=hav(current,c);const rest=remaining.filter(y=>y.iso2!==c.iso2);const future=rest.length?Math.min(...rest.map(y=>hav(c,y))):0;const score=1/(1+local/2500)+0.35/(1+future/1800)+0.12*(c.region===current.region?1:0);return {iso2:c.iso2,score}}).sort((a,b)=>b.score-a.score);const max=scored[0]?.score||1;return scored.map(s=>({iso2:s.iso2,score:s.score/max}))}
export async function GET(){return NextResponse.json({configured:Boolean(process.env.JEV_API_URL&&process.env.JEV_API_KEY)})}
export async function POST(req:Request){
 const started=Date.now(); const body=(await req.json()) as DecideRequest; const url=process.env.JEV_API_URL; const key=process.env.JEV_API_KEY; const model=process.env.JEV_MODEL||"jev-latest";
 if(!url||!key)return NextResponse.json({mode:"demo",ranked:demoRank(body.current,body.candidates,body.remaining),latencyMs:Date.now()-started});
 const criteria:Record<string,string>={}; for(const c of body.candidates){const f=body.distanceFeatures?.find(x=>x.iso2===c.iso2); criteria[c.iso2]=body.mode==="distance"&&f ? JSON.stringify({capital:c.capital,country:c.country,current_km:Math.round(f.currentKm),nearest_future_km:Math.round(f.nearestFutureKm),farthest_future_km:Math.round(f.farthestFutureKm)}) : c.capital+", "+c.country;}
 try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+key},body:JSON.stringify({state:{task:"round-the-world capital tour",current:{iso2:body.current.iso2,capital:body.current.capital},remaining_count:body.remaining.length,candidates:body.candidates.map(c=>c.iso2),features:body.distanceFeatures||undefined,matrix:body.mode==="matrix"?body.distanceMatrix:undefined},model,questions:{next_capital:{type:"choice",instructions:"Choose exactly one supplied candidate. Minimize expected total remaining travel distance. In distance mode, use the supplied current/nearest/farthest distance features. In matrix mode, use the supplied distance matrix. Never choose outside the supplied candidates.",criteria},route_strategy:{type:"choice",instructions:"Choose the routing strategy that should guide the surrounding deterministic policy for this step.",criteria:{cluster:"Prefer entering a dense nearby cluster and keeping future legs short.",isolate:"Prefer serving a geographically isolated or hard-to-reach area before it becomes stranded.",bridge:"Prefer a geographically central transition that connects remaining clusters efficiently."}}}})});
  if(!r.ok){const errText=await r.text();return NextResponse.json({error:"JEV provider request failed ("+r.status+"): "+errText.slice(0,300)},{status:502})}
  const data=await r.json(); const answer=data?.answers?.next_capital; const strategyAnswer=data?.answers?.route_strategy;
  if(!answer||answer.type!=="choice"||!answer.probabilities)return NextResponse.json({error:"JEV provider returned an unexpected choice response"},{status:502});
  const strategy=strategyAnswer?.type==="choice"&&strategyAnswer.probabilities?Object.entries(strategyAnswer.probabilities).sort((a:any,b:any)=>b[1]-a[1])[0]?.[0]:"bridge";
  const ranked=body.candidates.map(c=>({iso2:c.iso2,confidence:answer.probabilities[c.iso2]??0})).sort((a,b)=>b.confidence-a.confidence);
  if(!ranked.length)return NextResponse.json({error:"JEV provider returned no candidate scores"},{status:502});
  return NextResponse.json({mode:"live",ranked,model,strategy,latencyMs:Date.now()-started,contextMode:body.mode||"geographic"});
 }catch(e:any){return NextResponse.json({error:"JEV provider request errored",message:e?.message||String(e)},{status:502})}
}